### ISSUE TITLE
Further cleanup needed for Pull 101

### ISSUE THREAD

**Issue by microguy** [goldcoin/Goldcoin-GLD#118]
Our developers have patched most of the bad changes in this merge. There are still a few remaining.

I'm opening this issue, until all of the bad code can be corrected.

**Comment by Reaper-lk** [comment]
![image](https://user-images.githubusercontent.com/86299599/206807178-83529acb-2931-45f5-8aa5-52cdaba46300.png)   want to revert this!

**Comment by microguy** [comment]
This is another fix needed that breaks the default .conf:

![image](https://user-images.githubusercontent.com/4760093/206807413-b3531d83-55f7-4451-98ec-b4dbcca0a575.png)

I'll work on this in the morning. I guess this is "clean Tyler's mess up" week at Goldcoin.  We don't need the default config to be a novel. Just a short story.

And RPC is 8122 !!!!!!!!!!!!!!!!!!!

**Comment by microguy** [comment]
Damn it.....

![image](https://user-images.githubusercontent.com/4760093/206810978-092be338-b5c5-4f74-b825-1ac96f21e345.png)

A blind man will lead a blind man into a hole.

**Comment by microguy** [comment]
> This is another fix needed that breaks the default .conf:
> 
> ![image](https://user-images.githubusercontent.com/4760093/206807413-b3531d83-55f7-4451-98ec-b4dbcca0a575.png)
> 
> I'll work on this in the morning. I guess this is "clean Tyler's mess up" week at Goldcoin. We don't need the default config to be a novel. Just a short story.
> 
> And RPC is 8122 !!!!!!!!!!!!!!!!!!!

We don't need the default settings to be specified in the goldcoin.conf. There's no point in that.

That file is designed for when we want to use things other than default. I'm going to revert that commit altogether.

This is the dogecoin approach. That file in their repo is precisely that commit reverted.

**Comment by microguy** [comment]
This issue has been resolved in pull #119
