### ISSUE TITLE
Difficulty Adjustment Bug

### ISSUE THREAD

**Issue by microguy** [goldcoin/Goldcoin-GLD#122]
Last week, a new bug was discovered in the latest Goldcoin version release (0.14.9.1) that breaks the Golden River difficulty adjustment algorithm.

In order to consolidate the various channels where this issue is currently being discussed, I am opening the issue here, where those most capable and qualified in fixing the problem can work together on a solution.

**There are three options that come to mind:**

1. Revert to the last known working release. This would be version 0.14.8. However, this version is loaded with other known bugs including: a now-patched null validation bug, improper handling of 32 MB blocks, and a vulnerability to recent dust attacks.

2. Install a new difficulty adjustment algorithm and release a patch to the latest version.
 
3. Fix Golden River and release a patch to the latest version.

My current thinking is option 3 is the most attractive. Further investigation is needed to fully appreciate the pros and cons of options 2 and 3.

I recommend we listen, take some time to discuss here, and work to find the best solution. Once we have arrived on a consensus solution, a pull request should be made and the patch merged and immediately deployed.

**Comment by freelancerstudio** [comment]
We have 19.1 and working properly

**Comment by microguy** [comment]
It has come to my attention that the Golden River difficulty algo is dependent on the 51% defense system.

We should be able to revert the recent commit in 0.14.9.1 that removed the 51% defense system and have a solid functional client. That's the quick fix. The long-term solution provided in Discord by @Stouse49 requires replacing Golden River.

These discussions are currently ongoing in Discord. I will update this thread once we have made a decision, We may go ahead and replace or patch Golden River.

**Comment by microguy** [comment]
This issue has been resolved in version 0.14.9.5.

We will build binaries and provide instructions for out of sync clients later this week.

**Comment by FortunerLegender** [comment]
> 

regards. I am Yohni Hartono from Indonesia (yohnihartono@gmail.com). I transferred 10,000 GLC on January 3, 2023 from my GLC wallet at Southexchange to my GLC wallet also at Freiexchange, but until now it hasn't been received. Is there any solution? Thank you

**Comment by microguy** [comment]
> > 
> 
> regards. I am Yohni Hartono from Indonesia ([yohnihartono@gmail.com](mailto:yohnihartono@gmail.com)). I transferred 10,000 GLC on January 3, 2023 from my GLC wallet at Southexchange to my GLC wallet also at Freiexchange, but until now it hasn't been received. Is there any solution? Thank you

We have reverted latest release to 0.14.9. Once we have the chain moving your deposit should post.

**Comment by microguy** [comment]
This issue has been fully resolved. Please visit the latest release page for instructions on upgrading:

https://github.com/goldcoin/goldcoin/releases/tag/v0.14.9.5

Our developers are available 24/7 in the #support channel of our Discord if you require assistance:

https://discord.me/goldcoin

**Comment by FortunerLegender** [comment]
excuse me. the coins that I transferred on January 3 from Southexchange haven't entered Freiexchange until now, does that mean the coins were lost due to an update?

**Comment by microguy** [comment]
> excuse me. the coins that I transferred on January 3 from Southexchange haven't entered Freiexchange until now, does that mean the coins were lost due to an update?

To check the status of a tx, you can use the block explorer: https://chainz.cryptoid.info/glc/
