### ISSUE TITLE
Define extended private and public key prefixes

### ISSUE THREAD

**Issue by Stouse49** [goldcoin/Goldcoin-GLD#29]
Bitcoin uses xpub and xprv for mainnet.  tpub and tprv for TestNet.

After determining the values for GoldCoin, update the chainparams.cpp file.

**Comment by microguy** [comment]
Just checking over the pull requests today and discovered this outstanding issue. Since this issue pertains to an outdated version and is 4 years old, I'm taking the liberty to close it. If this is still an open issue, please reopen.
