### ISSUE TITLE
Sent coins from my wallet but they still show 0/6 confirmations after 24hrs

### ISSUE THREAD

**Issue by trackmaxi** [goldcoin/Goldcoin-GLD#34]
I sent a test coin from my wallet which arrived at the destination quickly, I then sent my balance to the same destination and it's still sat there with 0/6 confirmations after over 24hrs. 
My balance now shows zero in my wallet.
I've also sent one coin back and forth since the larger transfer and that worked ok, but the large balance isn't moving but also isn't available in my wallet

Status: 0/unconfirmed
Date: 04/06/2019 05:40
Debit: -12130.46301938 GLD
Net amount: -12130.46301938 GLD
Transaction ID: 14d44dd5bc0f90e00b6ab24ec33301b9a23ee9f2766cd81ffaaa930ba4239cd5

**Comment by Stouse49** [comment]
That transaction id doesn't show up on the block chain, which means the coins were not actually sent.

Did you try restarting the wallet?  Do you have connected peers?

**Comment by trackmaxi** [comment]
Hi, I have tried multiple times to restart the wallet and even left it a couple of weeks to see if syncing again works but nothing.
I've got a backup of the wallet from March 19 but there's no option in the wallet to restore from a backup?? And absolutely no information about using a backup??

Can anyone help on this?

Thanks

**Comment by Stouse49** [comment]
Restoring a backup is a manual process.  It requires replacing the wallet.dat file in a certain folder that is specified on the Help / Debug Window dialog box.  For instance mine says:  

C:\Users\Stouse49\AppData\Roaming\GoldCoin (GLD)\

However, before you consider restoring a backup, what do you see for "Number of Connections" on this box.  Mine says:  "1 (In: 0 / Out: 1)".  If yours says "0 (In: 0 / Out: 0)", then that is your problem.

No connections means that no coins will be sent.  The restoring the backup will not help in this case.  Let me know about your connections, then we can go from there.

**Comment by trackmaxi** [comment]
Where exactly am I looking for the connections? I see on the bottom right if i 'hover' it says 6 connections, please see image....
No mention of In or Out?
![Connections](https://user-images.githubusercontent.com/51402345/60602195-3d9a4680-9dab-11e9-850b-30daca3cf44e.JPG)

![image](https://user-images.githubusercontent.com/51402345/60602124-1c395a80-9dab-11e9-9be0-8d8e105e12a7.png)

**Comment by Stouse49** [comment]
Your screen shots show another place that connections are indicated (it doesn't matter about in / out).  

What does it say if you double click on the transaction that wasn't sent?

Here is an example of a successfully sent transaction:
```
Status: 1356 confirmations
Date: 7/1/2019 22:55
To: forwarder tg1q5ff660nnumw27zhtcr3pdm0032lf0ugj7ds6jl
Debit: -0.10000000 GLC
Transaction fee: -0.00002820 GLC
Net amount: -0.10002820 GLC
Transaction ID: 7616893c2aed3f44e1783d0ba6d27b83fddb5180e0b004a6d570dc290a028276
Transaction total size: 222 bytes
Transaction virtual size: 141 bytes
Output index: 1

```

**Comment by trackmaxi** [comment]
Hi, this is what my screen shows on the transaction

![image](https://user-images.githubusercontent.com/51402345/60683291-e79ecf00-9e8e-11e9-9567-b83a24677707.png)

**Comment by Stouse49** [comment]
What version are you using?  Help / About Goldcoin Core.

If you are using 0.7 then sending no longer works.  You will need to upgrade to 0.14.4

https://github.com/goldcoin/goldcoin/releases/tag/v0.14.4

**Comment by trackmaxi** [comment]
I'm using version 07.5 apparently. This account sent one coin with no issue at all, then I sent my balance and presto it's vanished! Sent within hours.....
 
![image](https://user-images.githubusercontent.com/51402345/60683546-339e4380-9e90-11e9-8d3b-9756f407d911.png)


![image](https://user-images.githubusercontent.com/51402345/60683594-719b6780-9e90-11e9-98b1-680f78321010.png)

**Comment by Stouse49** [comment]
Well on May 1, 2019, the version 0.7.5 transactions were supposed to be rejected by the network due to how they are signed.

I would recommend making a backup, upgrading to 0.14.4 and then starting the 0.14.4 client with the 
`-zapwallettxes` option.  This option will return your coins to your account so they can be spent again.

**Comment by trackmaxi** [comment]
Ok I will give it a try, fingers crossed this works!

**Comment by trackmaxi** [comment]
I haven't seen the option for the -zapwallettxes yet though?

![image](https://user-images.githubusercontent.com/51402345/60684519-0b194800-9e96-11e9-9e7b-1352113ffcc8.png)

**Comment by Stouse49** [comment]
start it this way from a command prompt or the Run command 

"C:\Program Files\GoldCoin (GLD)\goldcoin-qt.exe" -zapwallettxes
or if that doesn't work:
"C:\Program Files (x86)\GoldCoin (GLD)\goldcoin-qt.exe" -zapwallettxes

**Comment by trackmaxi** [comment]
Should I cancel what it's doing now then?

**Comment by Stouse49** [comment]
Yes, otherwise, it will have to happen again.

**Comment by trackmaxi** [comment]
Ok, I have shut down, used the 'RUN'command and pasted this:- C:\Program Files\GoldCoin (GLD)\goldcoin-qt.exe 

Now it has opened and restarted......

Thanks for your help on this!!

**Comment by trackmaxi** [comment]
Hi, This hasn't worked, I still have no coins in my balance.....

![image](https://user-images.githubusercontent.com/51402345/60754065-c72c5d00-9fd3-11e9-9b15-0218adcbabeb.png)

**Comment by trackmaxi** [comment]
This is the message from the transaction screen...

![image](https://user-images.githubusercontent.com/51402345/60754185-4ec69b80-9fd5-11e9-9e96-6d1109622786.png)

**Comment by trackmaxi** [comment]
Hi, can you offer some more help what I need to do to recover my coins please, I can't see how they can just vanish?

Thanks

**Comment by trackmaxi** [comment]
Are you still able to help?

**Comment by Stouse49** [comment]
Your coins didn't vanish.  They are still on the blockchain and you still have the private keys for them.

Earlier you said that you pasted this command:
`C:\Program Files\GoldCoin (GLD)\goldcoin-qt.exe`

But you have to do this:
`"C:\Program Files\GoldCoin (GLD)\goldcoin-qt.exe" -zapwallettxes`

Without the `-zapwallettxes` at the end it is the same as clicking the icon to start the program and nothing will change.  If you did put the `-zapwallettxes` at the end and it didn't work, then we will try something else.

What `-zapwallettxes` does it is erases all transactions and then finds them again in the blockchain.  The 12,000 missing coins were never sent out and that transaction should disappear after the process completes.  Then your balance will include the 12,000 that is "missing".

**Comment by trackmaxi** [comment]
Hi, appologies, I thought that was just a comment. I will try it now....

I thought it was just everything within the inverted commas...

**Comment by trackmaxi** [comment]
Huuuuge thanks for helping solve this, as soon as it rebooted using that method all my coins are back in my wallet again!!

Thanks!!!

**Comment by Stouse49** [comment]
Excellent.  Good Work!
