### ISSUE TITLE
Double-Check Checkpoints

### ISSUE THREAD

**Issue by microguy** [goldcoin/Goldcoin-GLD#49]
We need to double-check these entries before releasing 0.14.9.

https://github.com/goldcoin/goldcoin/commit/7accfecf9a0882eb77f81ff5356499d7a962a69e

I don't fully understand them, or their purpose.

**Comment by Stouse49** [comment]
Checkpoints are useful in keeping a syncing client on the correct chain.  In the past we generally put a checkpoint on the blocks that were from a hard fork.  We don't have to add more checkpoints.  

The last checkpoint corresponds to the first block that was larger than 2 MB.

**Comment by microguy** [comment]
Thank you Stouse for this explanation. I will now close this issue.
