### ISSUE TITLE
Double-Check parameter for reserved coinbase TX

### ISSUE THREAD

**Issue by microguy** [goldcoin/Goldcoin-GLD#55]
Double-Check 1 KB setting for reserving space in the block assembler for the coinbase transaction.

```
// Reserve space for coinbase tx
    nBlockSize = 1000;
    nBlockSigOpsCost = 100;
```
https://github.com/goldcoin/goldcoin/blob/goldcoin-master/src/miner.cpp

Litecoin which has a maximum block weight of 4 MB (probably not relevant), uses 4 KB for this setting.

**Comment by Stouse49** [comment]
Not sure.  transactions are probably still limited to 100K bytes.

Perhaps the comment is misleading.   In other places there is a `- 1000` and perhaps 1000 bytes is reserved for the coinbase tx.

**Comment by microguy** [comment]
> Not sure. transactions are probably still limited to 100K bytes.
> 
> Perhaps the comment is misleading. In other places there is a `- 1000` and perhaps 1000 bytes is reserved for the coinbase tx.

Thank you Stouse for this information. I'll do some more digging tomorrow.

Looks like it's safe to consider this a low priority.

**Comment by microguy** [comment]
This setting has been verified as correct.
