### ISSUE TITLE
Setup RegTest Parameters

### ISSUE THREAD

**Issue by Stouse49** [goldcoin/Goldcoin-GLD#7]
### Describe the issue
Learn the purpose of RegTest (https://bitcoin.org/en/developer-examples#regtest-mode) and set up the parameters.  

### Is this a bug in the codebase(not a usage issue) that needs to be fixed?
It is in the codebase, but will not affect MainNet or TestNet.

#### What files need to be fixed? (Please list them all)
chainparams.cpp in commit 7dbd1ea7834e2b6e0163d12ac341dc6d30688518

These parts were removed or replaced - RegTest is supposed to have a very very low difficulty to allow blocks to be generated very quickly with a CPU:
`consensus.powLimit = uint256S("7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");`
```
// By default assume that the signatures in ancestors of this block are valid.
consensus.defaultAssumeValid = uint256S("0x00");
```
And from Params, this was removed:
`uint256 defaultAssumeValid;`

Other parts of "defaultAssumeValid" were also removed (init.cpp - it is a command line parameter).

#### Why?
So RegTest will work as intended.  Though it is possible no one will ever use it.

EDIT:  The qa/pull-tester/rpc-tests.py tests use this.

**Comment by akumaburn** [comment]
Noted its probably a good idea additionally to do our testing on regtest first so we can speed things up.

**Comment by Stouse49** [comment]
RegTest is a system that can be used to quickly generate blocks to test some basic functions of the client and then to test any other local software that watches the blockchain or sends/receives coins.  This mode doesn't need a 51% Defense or GoldenRiver, so we should set those fork parameters to a very high block count, one that is never reached.

Resolving this issue will help resolve Issue #3.
