### ISSUE TITLE
Bug: Building Windows using Git Instructions

### ISSUE THREAD

**Issue by microguy** [goldcoin/Goldcoin-GLD#96]
Today, I attempted to make a Windows binary on Ubuntu 22 using the following guide : 

https://github.com/goldcoin/goldcoin/blob/goldcoin-master/doc/build-windows.md

This build failed with the following error:

`make: *** [funcs.mk:244: /root/goldcoin/depends/work/build/x86_64-w64-mingw32/boost/1_64_0-bf72c87e006/./.stamp_built] Error 1`

Spock is preparing to make a few PRs that will update our git dependencies. Once these are merged, we should update the instructions on the linked manual.

**Comment by expatjedi** [comment]
Tonight I compiled our source code for windows wallet on ubuntu 22.04 following the guide instructions and did not encounter any problems. The build completed without any errors and was tested on a computer with windows 10. Wallet functions and sync works well.

**Comment by microguy** [comment]
I did find a couple of problems when building on a fresh Windows 10 environment. The updated Bitcoin docs addresses this issue. I'll get our documentation updated ASAP.

**Comment by microguy** [comment]
Updated WSL instructions have been added to the page:

https://github.com/goldcoin/goldcoin/blob/goldcoin-master/doc/build-windows.md

This issue can now be closed.
